# Generated by Django 4.1.7 on 2023-04-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('budget', models.IntegerField(default=0)),
                ('dates', models.CharField(max_length=100)),
                ('flights', models.CharField(max_length=100)),
                ('hotel', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=300)),
            ],
        ),
    ]
