# Generated by Django 4.1.7 on 2023-04-29 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_destination_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursions',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.destination'),
        ),
    ]
